# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

ENV["OTP_ISSUER"] = "Jingle Jam (test)"
ENV["TWITCH_EMBED_ENABLED"] = "false"

require "cucumber/rails"

require "webdrivers"
require "webdrivers/chromedriver"

require "webmock/cucumber"
driver_urls = Webdrivers::Common.subclasses.map(&:base_url)
WebMock.disable_net_connect!(allow_localhost: true, allow: driver_urls)

require "rspec/mocks"
FactoryBot.find_definitions

require "sidekiq/testing"
Sidekiq::Testing.inline!

require_relative "../../test/support/with_env"
World(WithEnv)

Capybara.configure do |config|
  config.server = :puma, { Silent: true }
end

ActionController::Base.allow_rescue = false

begin
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Before do
  page.driver.browser.manage.window.maximize
end

After do
  ::RSpec::Mocks.verify
ensure
  ::RSpec::Mocks.teardown
end

Around("@twitch_embed_enabled") do |_, scenario|
  with_env("TWITCH_EMBED_ENABLED" => "true") do
    scenario.call
  end
end
