AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - bin/**/*
    - script/**/*
    - config/**/*
    - lib/tasks/cucumber.rake
    - lib/tasks/auto_annotate_models.rake
    - /**/*.erb
    - vendor/**/*
  <% `git status --ignored --porcelain`.scan(/^!!\s+(.*)$/).each do |match| %>
    - <%= match[0] %>**/*
  <% end %>

# Extensions
require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

# New rules
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
Gemspec/DateAssignment: # (new in 1.10)
  Enabled: true
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: true
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashConversion: # (new in 1.10)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true

Rails/ActiveRecordCallbacksOrder: # (new in 2.7)
  Enabled: true
Rails/AfterCommitOverride: # (new in 2.8)
  Enabled: true
Rails/AttributeDefaultBlockValue: # (new in 2.9)
  Enabled: true
Rails/FindById: # (new in 2.7)
  Enabled: true
Rails/Inquiry: # (new in 2.7)
  Enabled: true
Rails/MailerName: # (new in 2.7)
  Enabled: true
Rails/MatchRoute: # (new in 2.7)
  Enabled: true
Rails/NegateInclude: # (new in 2.7)
  Enabled: true
Rails/Pluck: # (new in 2.7)
  Enabled: true
Rails/PluckInWhere: # (new in 2.7)
  Enabled: true
Rails/RenderInline: # (new in 2.7)
  Enabled: true
Rails/RenderPlainText: # (new in 2.7)
  Enabled: true
Rails/ShortI18n: # (new in 2.7)
  Enabled: true
Rails/SquishedSQLHeredocs: # (new in 2.8)
  Enabled: true
Rails/WhereEquals: # (new in 2.9)
  Enabled: true
Rails/WhereExists: # (new in 2.7)
  Enabled: true
Rails/WhereNot: # (new in 2.8)
  Enabled: true

# Alterations
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/BlockComments:
  Exclude:
    - spec/**/*
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ContextWording:
  Prefixes:
    - but
    - if
    - when
    - with
    - without
RSpec/AnyInstance:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - spec/**/*
Layout/ArgumentAlignment:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
Style/AsciiComments:
  Enabled: false
Layout/CaseIndentation:
  EnforcedStyle: end
Rails/RakeEnvironment:
  Enabled: false
Style/Lambda:
  Enabled: false
Layout/SpaceInLambdaLiteral:
  Enabled: false
Layout/IndentationWidth:
  Exclude:
    - lib/tasks/*
Style/RedundantSelf:
  Enabled: false
Style/PreferredHashMethods:
  EnforcedStyle: verbose
Style/IfUnlessModifier:
  Enabled: false
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: true
Naming/AccessorMethodName:
  Exclude:
    - app/controllers/**/*
Style/GuardClause:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/MethodParameterName:
  AllowedNames:
    - as
    - id
Layout/LineLength:
  Exclude:
    - features/**/*_steps.rb
Metrics/AbcSize:
  Enabled: false
Style/IfUnlessModifierOfIfUnless:
  Enabled: false
Style/NestedModifier:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case
Metrics/ModuleLength:
  Exclude:
    - test/**/*
