# https://docs.docker.com/samples/rails/

version: "3.9"  # optional since v1.27.0
services:
    db:
        image: postgres:11
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=jinglejam
    web:
        build: .
        command: bash -c "rm -f /jinglejam/tmp/pids/server.pid && RAILS_ENV=development bundle exec rails server -p 3000 -b 0.0.0.0"
        volumes:
            - .:/jinglejam
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            - FROM_EMAIL_ADDRESS=jingle-jam@example.com
            - HMAC_SECRET=c360bcae-df63-4616-808a-860f03d7da6b
            - DATABASE_URL=postgres://postgres:password@db/jingle_jam_development
