version: 2.1

orbs:
  ruby: circleci/ruby@1.4
  node: circleci/node@5.0
  browser-tools: circleci/browser-tools@1.2

jobs:
  test:  # our next job, called "test"
    docker:
      - image: cimg/ruby:3.1.1-browsers # this is our primary docker image, where step commands run.
      - image: cimg/postgres:13.5
        environment: # add POSTGRES environment variables.
          POSTGRES_USER: circleci
          POSTGRES_DB: jingle_jam_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    # environment variables specific to Ruby/Rails, applied to the primary container.
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      CI: true
      FROM_EMAIL_ADDRESS: "jingle-jam@example.com"
      HMAC_SECRET: "c360bcae-df63-4616-808a-860f03d7da6b"
      PAYPAL_API_ENDPOINT: "https://api.paypal.example.com"
      PAYPAL_CLIENT_ID: "AakBwrFPLdPU4-oKX939jxpGlL-0_J9E10z1dSapKjp2G-o8pte9OjKw8bBlQEHKbyFWU9WqAdTMgupz"
      PAYPAL_EMAIL_ADDRESS: "abcde@example.com"
      PAYPAL_MERCHANT_ID: "abcde"
      PAYPAL_WEBHOOK_ID: "abcde"
      PGHOST: 127.0.0.1
      PGPASSWORD: ""
      PGUSER: circleci
      STRIPE_PUBLIC_KEY: "pk_test_a67ef84afbf01ea3d84adda4fabc4adc"
      STRIPE_SECRET_KEY: "sk_test_9800ec742bc5b49f66fc6430c7359b3d"
      STRIPE_WEBHOOK_SECRET_KEY: "whsec_ab50669157228f63305e8fea9244baa2"
    steps:
      - browser-tools/install-chrome:
          replace-existing: true
      - browser-tools/install-chromedriver
      - run:
          name: Check install
          command: |
            google-chrome --version
            chromedriver --version
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          with-cache: true
      # Here we make sure that the secondary container boots
      # up before we run operations on the database.
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: RAILS_ENV=test bundle exec rails db:schema:load --trace
      - run:
          name: Tests
          command: bundle exec rake

workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - test          # Then run test,
